---
language: python
sudo: required
services:
  - docker

# Bug in docker-compose version 1.17.1: ${VAR:-} syntax incorrectly parsed
# https://github.com/docker/compose/blob/master/CHANGELOG.md#bugfixes-11
# https://docs.travis-ci.com/user/docker/#using-docker-compose
env:
  - DOCKER_COMPOSE_VERSION=1.18.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose version
  - docker version
  - ./test.sh

after_failure:
  - docker-compose logs
